"""Canonical WAIKE UPNOW site registry for campus design and curriculum."""
from __future__ import annotations

from typing import Any

SITE_IDS = ["gary", "ghana", "guyana", "gaza", "geelong", "graham_land", "germany"]

WEEK_TOPICS = [
    "Place, ethics, public benefit, and local accountability",
    "Digital foundations, device readiness, and safety",
    "Networking and connectivity (Wi-Fi, wired, cellular, edge, NTN where relevant)",
    "Hardware, repair, sensors, safety, and maintenance",
    "Software, web, app foundations, and documentation",
    "Cybersecurity, privacy, data protection, and threat modeling",
    "Cloud, AI literacy, edge AI, responsible AI, and evaluation",
    "Site-specific applied systems",
    "Campus/building design studio: room program, acoustics, RF, power, safety",
    "Community project sprint",
    "Portfolio, certifications, career/apprenticeship/scholarship readiness",
    "Final capstone demo and public/private presentation",
]

ASSIGNMENT_TITLES = [
    "Place-based ethics and non-claim memo",
    "Learner device and access audit",
    "Connectivity and resilience worksheet",
    "Hardware, repair, and sensor safety plan",
    "Software or web project",
    "Cybersecurity and privacy tabletop",
    "AI, cloud, and edge workflow",
    "Site-specific applied systems project",
    "Room program and acoustic/RF tradeoff memo",
    "Conceptual floor plan",
    "Final capstone report",
    "Final presentation deck outline",
]

LAB_TITLES = [
    "Local digital access map",
    "Network diagram and connectivity audit",
    "Link budget or coverage model (where relevant)",
    "Device repair, sensor, and hardware safety lab",
    "Lightweight website or dashboard",
    "Cyber hygiene tabletop",
    "AI/cloud notebook or offline workflow",
    "Site-specific applied system lab",
    "Building material matrix and scoring",
    "Acoustic/RF room boundary scoring",
    "Floor plan adjacency graph",
    "Final integrated demo",
]

SHARED_ROOMS = [
    "welcome_intake",
    "flexible_classroom",
    "device_bar",
    "hardware_repair_lab",
    "networking_cyber_lab",
    "ai_cloud_studio",
    "career_portfolio_studio",
    "community_room",
    "staff_mentor_workspace",
    "secure_storage",
    "quiet_decompression",
    "hybrid_learning_corner",
    "server_comms_closet",
    "mechanical_electrical_zone",
    "public_exhibit_wall",
]

SITE_REGISTRY: dict[str, dict[str, Any]] = {
    "gary": {
        "display_name": "WAIKE Gary UPNOW",
        "subtitle": "Wireless + Artificial Intelligence Kinesthetic Education",
        "tagline": "For Gary Indiana's Undiscovered Professionals Navigating Opportunities Wherever",
        "course_title": "WAIKE Gary UPNOW: Build, Certify, Ship",
        "anchor": "Gary, Indiana",
        "role": "Flagship proof campus and civic workforce school",
        "extra_rooms": [
            "civic_tech_studio",
            "student_showcase_wall",
            "small_business_help_desk",
            "ai_ran_edge_lab",
            "game_jam_demo_zone",
        ],
        "modules": [
            "digital equity",
            "IT support",
            "device bar operations",
            "AI-RAN basics",
            "edge devices",
            "community connectivity",
            "cyber hygiene for small organizations",
            "local civic projects",
            "resume/portfolio readiness",
        ],
        "network_emphasis": "AI-RAN/edge learning, community Wi-Fi mapping, lab segmentation",
        "building_typologies": [
            "pop-up library/community lab",
            "retrofit storefront/civic building",
            "full Gary WAIKE UPNOW campus",
        ],
    },
    "ghana": {
        "display_name": "WAIKE Ghana UPNOW",
        "subtitle": "Wireless + Artificial Intelligence Kinesthetic Education",
        "tagline": "For Ghana's Undiscovered Professionals Navigating Opportunities Wherever",
        "course_title": "WAIKE Ghana UPNOW: Build, Ship, Serve",
        "anchor": "Accra–Tema corridor",
        "role": "Pan-African technology, entrepreneurship, mobile-first, and digital inclusion node",
        "extra_rooms": [
            "mobile_first_studio",
            "repair_refurb_bench",
            "entrepreneurship_clinic",
            "rural_popup_depot",
            "diaspora_mentor_room",
        ],
        "modules": [
            "mobile-first learning",
            "phone-to-laptop transition",
            "SME website clinics",
            "mobile money safety",
            "repair/refurbishment",
            "entrepreneurship",
            "rural pop-up lab operations",
            "diaspora mentorship",
        ],
        "network_emphasis": "mobile-first, shared device onboarding, rural fallback, offline workshop packs",
        "building_typologies": [
            "university/hub/community pop-up",
            "retrofit civic/commercial hub in Accra–Tema",
            "full Ghana WAIKE UPNOW campus with regional pop-up depot",
        ],
    },
    "guyana": {
        "display_name": "WAIKE Guyana UPNOW",
        "subtitle": "Wireless + Artificial Intelligence Kinesthetic Education",
        "tagline": "For Guyana's Undiscovered Professionals Navigating Opportunities Wherever",
        "course_title": "WAIKE Guyana UPNOW: Build, Map, Resilient Futures",
        "anchor": "Georgetown–Demerara corridor",
        "role": "South America + Caribbean bridge, climate resilience, river/logistics workforce node",
        "extra_rooms": [
            "climate_gis_studio",
            "river_logistics_studio",
            "energy_systems_studio",
            "flood_literacy_wall",
            "interior_kit_depot",
        ],
        "modules": [
            "climate/flood data literacy",
            "GIS and drainage mapping",
            "river/port/logistics systems",
            "oil-and-non-oil career pathways",
            "Indigenous/community consent",
            "low-bandwidth interior learning",
            "agriculture sensors",
            "CARICOM/regional bridge",
        ],
        "network_emphasis": "flood-resilient connectivity, elevated equipment, regional low-bandwidth routes",
        "building_typologies": [
            "public agency / university / community pop-up",
            "retrofit civic or commercial building in Georgetown–Demerara",
            "full climate-tech and workforce campus with regional route storage",
        ],
    },
    "gaza": {
        "display_name": "WAIKE Gaza UPNOW",
        "subtitle": "Wireless + Artificial Intelligence Kinesthetic Education",
        "tagline": "For Gaza's Undiscovered Professionals Navigating Opportunities Wherever",
        "course_title": "WAIKE Gaza UPNOW: Learn, Repair, Rebuild",
        "anchor": "Distributed Gaza Education Recovery Network (no fixed public site)",
        "role": "Palestinian-led recovery education, trauma-informed, offline-first learning network",
        "extra_rooms": [
            "safe_intake_point",
            "temporary_learning_circle",
            "offline_kit_station",
            "teacher_support_station",
            "caregiver_guide_station",
            "device_clinic",
            "solar_charging_station",
            "reconstruction_doc_studio",
            "psychosocial_decompression",
            "mobile_kit_storage",
        ],
        "modules": [
            "trauma-informed learning",
            "offline-first curriculum",
            "teacher support kits",
            "caregiver guides",
            "child protection",
            "device repair",
            "solar charging safety",
            "digital safety",
            "reconstruction documentation",
            "portfolio recovery",
        ],
        "network_emphasis": "offline-first, local content server, shared-device workflows, privacy-first",
        "building_typologies": [
            "fully remote/diaspora-supported learning network",
            "partner-led temporary learning space network",
            "future permanent recovery campus after safety and expert review",
        ],
        "privacy_sensitive": True,
    },
    "geelong": {
        "display_name": "WAIKE Geelong UPNOW",
        "subtitle": "Wireless + Artificial Intelligence Kinesthetic Education",
        "tagline": "For Geelong's Undiscovered Professionals Navigating Opportunities Wherever",
        "course_title": "WAIKE Geelong UPNOW: Design, Build, Ship",
        "anchor": "Central Geelong–Waurn Ponds corridor",
        "role": "Design, advanced manufacturing, health-tech, port/logistics, coastal climate node",
        "extra_rooms": [
            "design_build_studio",
            "manufacturing_sensor_bench",
            "health_sports_tech_demo",
            "coastal_climate_station",
            "northern_geelong_depot",
            "design_critique_room",
        ],
        "modules": [
            "design/build studio",
            "manufacturing transition",
            "health-tech",
            "sports-tech",
            "port/logistics",
            "clean energy",
            "coastal/climate awareness",
            "northern Geelong inclusion",
            "Traditional Owner consultation note",
        ],
        "network_emphasis": "industrial/design/build labs, coastal sensor demos, port/logistics learning networks",
        "building_typologies": [
            "university/TAFE/community pop-up",
            "retrofit industrial/design/civic building",
            "full applied technology and design campus",
        ],
    },
    "graham_land": {
        "display_name": "WAIKE Graham Land UPNOW",
        "subtitle": "Wireless + Artificial Intelligence Kinesthetic Education",
        "tagline": "For Graham Land's Undiscovered Professionals Navigating Opportunities Wherever",
        "course_title": "WAIKE Graham Land UPNOW: Sense, Simulate, Steward",
        "anchor": "Remote-first Graham Land Digital Twin and Polar Learning Node",
        "role": "Remote-first polar research, NTN, extreme connectivity, climate data, stewardship node",
        "extra_rooms": [
            "polar_digital_twin_studio",
            "climate_data_lab",
            "gis_remote_sensing_studio",
            "ntn_satellite_lab",
            "field_safety_classroom",
            "robotics_sensor_bench",
            "battery_power_safety_bench",
            "cold_vestibule_simulation",
            "polar_education_exhibit",
        ],
        "modules": [
            "Antarctic stewardship",
            "non-claim policy",
            "NTN fundamentals",
            "LEO/MEO/GEO",
            "delay/Doppler",
            "satellite backhaul/access",
            "store-and-forward",
            "edge cache",
            "remote sensing",
            "climate data",
            "robotics/sensors",
            "polar field safety",
        ],
        "network_emphasis": "NTN gateway model, LEO/GEO hybrid, store-and-forward, polar outage assumptions",
        "building_typologies": [
            "fully remote digital twin/data lab",
            "non-Antarctic partner-hosted polar education studio",
            "future partner-approved field-adjacent concept only",
        ],
        "conceptual_only": True,
    },
    "germany": {
        "display_name": "WAIKE Germany UPNOW",
        "subtitle": "Wireless + Artificial Intelligence Kinesthetic Education",
        "tagline": "For Germany's Undiscovered Professionals Navigating Opportunities Wherever",
        "course_title": "WAIKE Germany UPNOW: Build, Document, Apprentice",
        "anchor": "Ruhr / Rhine-Ruhr industrial transition corridor",
        "role": "Dual apprenticeship, Industry 4.0, applied engineering, worker-centered automation node",
        "extra_rooms": [
            "apprenticeship_studio",
            "technical_documentation_room",
            "mechatronics_lab",
            "industry40_twin_studio",
            "quality_safety_review_room",
            "industrial_cyber_range",
            "sme_digitalization_clinic",
        ],
        "modules": [
            "dual vocational training",
            "apprenticeship readiness",
            "technical documentation",
            "Industry 4.0",
            "mechatronics",
            "industrial networking",
            "GDPR-style privacy",
            "worker-centered automation",
            "Mittelstand/SME digitalization",
            "quality and safety checklists",
        ],
        "network_emphasis": "industrial network segmentation, mechatronics/OT training, cybersecurity range",
        "building_typologies": [
            "vocational school/community pop-up",
            "retrofit industrial/civic building in Ruhr",
            "full applied technology and apprenticeship campus",
        ],
    },
}


def get_site(site_id: str) -> dict[str, Any]:
    if site_id not in SITE_REGISTRY:
        raise KeyError(f"Unknown site: {site_id}")
    return SITE_REGISTRY[site_id]
